spring.application.name=task-manager-backend
spring.datasource.url=jdbc:postgresql://ep-raspy-breeze-b5wgk7mz-pooler.c-7.us-east-2.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2am4zgyWHScY
spring.jpa.hibernate.ddl-auto=update
